### ISSUE TITLE
the 3 parameters no longer used by tiktok? 

### ISSUE THREAD

**Issue by cuckforlife** [LucioCarrera/tiktokapi-security#2]
Hey I did an MITM on my tiktok (Android) to check the API calls, I can't see the anti-spam parameters : 
as
cp
mas

They changed the security?

**Comment by LCSP** [comment]
Those parameters are being disabled by the app, the new endpoints have some others parameters/headers that are being used for checking (This repository is not longer maintained).
Feel free to contact me for further questions.
